version: "3"
services:
  #Laravel App
  app:
    build:
      context: .
      dockerfile: test.Dockerfile
    image: cominityteam/${BITBUCKET_REPO_SLUG}-${BITBUCKET_BRANCH}
    container_name: laravel
    restart: unless-stopped
    tty: true
    env_file: .env
    working_dir: /var/www
    volumes:
      - /var/www/vendor/
      - /var/www/node_modules/
      - ./:/var/www
      - ./ContainersConfig/php/local.ini:/usr/local/etc/php/conf.d/local.ini