version: "2.4"
services:
  #Laravel App
  app:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: app-${APP_NAME}
    depends_on:
      - "db"
    tty: true
    env_file: .env
    environment:
      - PHP_EXTENSION_XDEBUG=1
    working_dir: /var/www
    volumes:
      - /var/www/node_modules
      - ./:/var/www:delegated
      - ./ContainersConfig/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "80:8000"

  client:
    build:
      context: .
      dockerfile: node.Dockerfile
    command: "yarn watch"
    container_name: client-${APP_NAME}
    depends_on:
      - "app"
    tty: true
    env_file: .env
    working_dir: /node/app
    volumes:
      - /node/app/node_modules
      - ./:/node/app:delegated
    ports:
      # Port mapping for browser sync
      - "3000:3000"
      - "3001:3001"

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db-${APP_NAME}
    tty: true
    ports:
      - "3360:3360"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./ContainersConfig/mysql/my.cnf:/etc/mysql/my.cnf

  #PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-${APP_NAME}
    depends_on:
      - "db"
    ports:
      - "8080:80"
    volumes:
      - ./ContainersConfig/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    environment:
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

#Volumes
volumes:
  dbdata:
    driver: local
