version: "2.4"
services:
  #Laravel App
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app-${APP_NAME}
    image: cominity/laravel
    depends_on:
      db:
        condition: service_healthy
    tty: true
    env_file: .env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PHP_EXTENSION_XDEBUG=1
    working_dir: /var/www
    volumes:
      - /var/www/node_modules
      - ./:/var/www:delegated
      - ./ContainersConfig/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "3000:3000"
      - "3001:3001"

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver-${APP_NAME}
    depends_on:
      - app
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www:delegated
      - ./ContainersConfig/nginx/conf.d/:/etc/nginx/conf.d/
      # Uncomment for debugging
      # - ./ContainersConfig/nginx/logs/:/var/log/nginx/

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db-${APP_NAME}
    tty: true
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
    ports:
      - "3360:3360"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./ContainersConfig/mysql/my.cnf:/etc/mysql/my.cnf

  #PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-${APP_NAME}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - ./ContainersConfig/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    environment:
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

#Volumes
volumes:
  dbdata:
    driver: local
