version: "3"
services:
  #Laravel App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cominityteam/${BITBUCKET_REPO_SLUG}-${BITBUCKET_BRANCH}
    container_name: laravel
    depends_on:
      - webserver
      - db
    restart: unless-stopped
    tty: true
    env_file: .env
    working_dir: /var/www
    volumes:
      - /var/www/vendor/
      - /var/www/node_modules/
      - ./:/var/www
      - ./ContainersConfig/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./ContainersConfig/nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: mysql
    command: --init-file /data/application/init.sql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./ContainersConfig/mysql/init.sql:/data/application/init.sql
      - ./ContainersConfig/mysql/my.cnf:/etc/mysql/my.cnf
